[pytest]
addopts = --alluredir=reports/allure-results -v
log_cli = true
log_cli_level = INFO
markers =
    smoke: Quick, critical tests to ensure basic API availability.
    regression: Comprehensive tests that run the entire functional suite.
